version: '3.7'
services:
  app:
    image: app
    build: .
    ports:
      - target: 5000
        published: 80
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database2
    volumes:
      - type: volume
        target: /var/lib/database2
        source: sqldata
volumes:
  sqldata:





